export const resourceTypeLabels = {
  movies: 'Movies',
  podcasts: 'Podcasts',
  books: 'Books',
  places: 'Places',
  'tools-apps': 'Tools/Apps',
}

const data = [
  {
    slug: 'interstellar',
    title: 'Interstellar',
    type: 'movies',
    summary: 'A high-stakes sci-fi story about time, choice, and systems thinking.',
    note: 'Great reminder that constraints force better engineering decisions.',
    year: 2014,
    tags: ['sci-fi', 'systems-thinking'],
    url: 'https://www.imdb.com/title/tt0816692/',
    featured: true,
    dateAdded: '2026-03-01',
  },
  {
    slug: 'the-social-network',
    title: 'The Social Network',
    type: 'movies',
    summary: 'Fast-paced story of product building, ambition, and trade-offs.',
    note: 'Useful to reflect on speed vs. trust when building products.',
    year: 2010,
    tags: ['product', 'startup'],
    url: 'https://www.imdb.com/title/tt1285016/',
    dateAdded: '2026-02-22',
  },
  {
    slug: 'acquired',
    title: 'Acquired',
    type: 'podcasts',
    summary: 'Deep strategic breakdowns of iconic companies and product bets.',
    note: 'Sharp way to learn market context and long-term execution patterns.',
    platform: 'Spotify / Apple Podcasts',
    tags: ['strategy', 'business'],
    url: 'https://www.acquired.fm/',
    featured: true,
    dateAdded: '2026-02-25',
  },
  {
    slug: 'lenny-podcast',
    title: "Lenny's Podcast",
    type: 'podcasts',
    summary: 'Interviews on product, growth, and career execution.',
    note: 'Practical frameworks you can apply immediately in real projects.',
    platform: 'Spotify / Apple Podcasts',
    tags: ['product', 'growth'],
    url: 'https://www.lennysnewsletter.com/podcast',
    dateAdded: '2026-02-14',
  },
  {
    slug: 'deep-work',
    title: 'Deep Work',
    type: 'books',
    summary: 'A practical book on focus, output quality, and deliberate practice.',
    note: 'Helped me simplify how I structure coding sessions and delivery.',
    author: 'Cal Newport',
    year: 2016,
    tags: ['focus', 'productivity'],
    url: 'https://www.calnewport.com/books/deep-work/',
    featured: true,
    dateAdded: '2026-02-28',
  },
  {
    slug: 'atomic-habits',
    title: 'Atomic Habits',
    type: 'books',
    summary: 'Systematic approach to changing behavior through tiny habits.',
    note: 'Useful for making consistent progress in long technical projects.',
    author: 'James Clear',
    year: 2018,
    tags: ['habits', 'consistency'],
    url: 'https://jamesclear.com/atomic-habits',
    dateAdded: '2026-02-18',
  },
  {
    slug: 'station-f-coworking',
    title: 'Station F',
    type: 'places',
    summary: 'A startup-focused campus with strong build energy and community.',
    note: 'I like places that create momentum and focused work blocks.',
    location: 'Paris',
    tags: ['coworking', 'startup'],
    url: 'https://stationf.co/',
    dateAdded: '2026-02-10',
  },
  {
    slug: 'wework-casa-anfa',
    title: 'WeWork Casa Anfa',
    type: 'places',
    summary: 'Comfortable coworking setup with stable infrastructure for deep work.',
    note: 'Good option for long maker sessions and quiet execution.',
    location: 'Casablanca',
    tags: ['coworking', 'focus'],
    url: 'https://www.wework.com/',
    dateAdded: '2026-02-06',
  },
  {
    slug: 'notion',
    title: 'Notion',
    type: 'tools-apps',
    summary: 'Flexible docs/wiki workspace for personal systems and project context.',
    note: 'Great for connecting ideas, notes, and execution plans.',
    platform: 'Web / Desktop / Mobile',
    tags: ['notes', 'organization'],
    url: 'https://www.notion.so/',
    dateAdded: '2026-02-12',
  },
  {
    slug: 'raycast',
    title: 'Raycast',
    type: 'tools-apps',
    summary: 'Command launcher that removes friction in daily development workflows.',
    note: 'Small speedups compound across every day of work.',
    platform: 'macOS',
    tags: ['productivity', 'launcher'],
    url: 'https://www.raycast.com/',
    dateAdded: '2026-02-04',
  },
]

export const resources = [...data].sort(
  (a, b) => new Date(b.dateAdded) - new Date(a.dateAdded)
)

export const allResourceTypes = Object.keys(resourceTypeLabels)
